version: '3.9'

services:
  re_miner_bff:
    container_name: re_miner_bff
    build:
      context: ./
    env_file:
      - ./docker.env 
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    env_file:
      - ./db.env 
    volumes:
      - pgdata:/var/lib/postgresql/12/data
    ports:
      - "5432:5432"
    user: "postgres"


volumes:
  pgdata: {}