version: '3.9'

services:
  bff:
    container_name: bff
    build:
      context: ./
    env_file:
      - ./bff.env 
    ports:
      - "3003:3003"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    env_file:
      - ./db.env 
    volumes:
      - pgdata:/var/lib/postgresql/12/data
    ports:
      - "5432:5432"

volumes:
  pgdata: {}