# Use the official PostgreSQL image as a base
FROM postgres:12

# Copy custom configuration files if any
# COPY ./path/to/your/config/file /etc/postgresql/postgresql.conf

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=pg_strong_password
ENV POSTGRES_DB=dashboard_db

EXPOSE 5432

VOLUME ["/var/lib/postgresql/data"]

CMD ["postgres"]
